---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: myapp-deployment
        labels:
                app: webserver
                type: apach-webserver
spec:
        template:
            metadata:
               name: my-first-pod-mysql
               labels:
                   app: mysql
                   type: apache-mysql

            spec:
               containers:
                 - name: mysql
                   image: mysql:5.7 
                   envFrom:
                           - configMapRef: 
                                name: app-configmap

        replicas: 2
        selector:
                matchLabels:
                        type: apache-mysql
                        app: mysql

