---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: myapp-deployment
        labels:
                app: webserver
                type: apach-webserver
spec:
        template:
            metadata:
               name: my-first-pod-mysql
               labels:
                   app: mysql
                   type: apache-mysql

            spec:
               containers:
                 - name: mysql
                   image: mysql:5.7 
                  
                   env:
                     - name: MYSQL_ROOT_PASSWORD
                       value: "redhat"

                     - name: MYSQL_USER
                       value: "yogi"

                     - name: MYSQL_PASSWORD
                       value: "redhat"

                     - name: MYSQL_DATABASE
                       value: "lwdb"

        replicas: 2
        selector:
                matchLabels:
                        type: apache-mysql
                        app: mysql

