---
apiVersion: v1
kind: ResourceQuota
metadata:
        name: compute-quota
        namespace: dev
spec:
        hard:
                pods: "2"
                requests.cpu: "2"
                requests.memory: "2Gi"
                limits.cpu: "5"
                limits.memory: "5Gi"

