---
apiVersion: v1
kind: Pod
metadata:
        name: node-pod
spec:
        containers:
                - name: nginx
                  image: nginx
        nodeSelector:
                  size: large
