---
apiVersion: v1
kind: Pod
metadata:
        name: pod-tolerate
spec:
        containers:
                - name: nginx
                  image: nginx
        tolerations:
                - key: "app"
                  operator: "Equal"
                  value: "blue"
                  effect: "NoSchedule"
